version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb-services
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo-data:/data/db
      - ./import:/data/import

volumes:
  mongo-data:
